export const styles = `
:host{--green:#006a4e;--green-dark:#003f30;--green-soft:#e9f5f0;--blue:#155fa0;--gold:#f4b41a;--ink:#17231e;--muted:#6c7b74;--line:#e5ebe8;position:fixed;right:24px;bottom:24px;z-index:2147483000;font:14px/1.5 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink)}
*{box-sizing:border-box}button,textarea{font:inherit}.hidden{display:none!important}
.launcher{position:relative;width:76px;height:76px;padding:0;overflow:hidden;border:5px solid #e9b95e;border-radius:50%;cursor:pointer;display:grid;place-items:center;background:#fcb415;box-shadow:0 14px 34px #4b351f4d,0 3px 8px #00000024;transition:.2s ease}
.launcher:hover{transform:translateY(-3px) scale(1.03);box-shadow:0 18px 42px #4b351f59}.launcher img{display:block;width:100%;height:100%;object-fit:cover;object-position:center;border-radius:50%;transform:scale(1.08)}
.launcher:disabled{cursor:wait;opacity:.72;transform:none}
.panel{width:min(410px,calc(100vw - 28px));height:min(690px,calc(100vh - 48px));display:flex;flex-direction:column;background:#fff;border:1px solid #0d463314;border-radius:26px;overflow:hidden;box-shadow:0 28px 80px #132e253d,0 8px 26px #132e251f}
.header{position:relative;display:flex;align-items:center;gap:12px;padding:18px;color:#fff;background:linear-gradient(125deg,#006a4e 0%,#004f3c 58%,#163f69 130%)}
.header:after{content:"";position:absolute;inset:0;background:radial-gradient(circle at 85% -20%,#ffffff33,transparent 42%);pointer-events:none}.avatar{position:relative;z-index:1;width:45px;height:45px;border-radius:15px;display:grid;place-items:center;color:var(--green-dark);font-weight:800;background:linear-gradient(145deg,#fff,#eaf7f1);box-shadow:0 7px 18px #00000029}.status-dot{position:absolute;right:-2px;bottom:-2px;width:13px;height:13px;border-radius:50%;background:#4cdb89;border:3px solid #005440}
.identity{position:relative;z-index:1;min-width:0;flex:1}.identity strong{display:block;font-size:16px;line-height:1.25}.identity small{display:flex;align-items:center;gap:6px;margin-top:3px;color:#ffffffc7;font-size:11.5px}.online{width:6px;height:6px;border-radius:50%;background:#57e698}.header-action{position:relative;z-index:1;width:36px;height:36px;border:0;border-radius:11px;background:#ffffff1a;color:#fff;cursor:pointer;display:grid;place-items:center}.header-action:hover{background:#ffffff2e}.header-action svg{width:18px;height:18px}
.trustbar{display:flex;align-items:center;gap:7px;padding:9px 16px;color:#52645c;background:#f8fbfa;border-bottom:1px solid var(--line);font-size:11px}.trustbar svg{width:14px;height:14px;color:var(--green)}
.messages{flex:1;overflow:auto;padding:20px 16px 12px;background:linear-gradient(180deg,#f7faf9,#f2f6f4);scroll-behavior:smooth}.message-row{display:flex;align-items:flex-end;gap:8px;margin-bottom:15px}.message-row.user{justify-content:flex-end}.mini-avatar{flex:0 0 auto;width:28px;height:28px;border-radius:10px;display:grid;place-items:center;background:var(--green);color:#fff;font-size:9px;font-weight:800;box-shadow:0 3px 10px #00503a26}.message-stack{max-width:82%}.bubble{padding:11px 13px;border-radius:17px;white-space:pre-wrap;overflow-wrap:anywhere;box-shadow:0 3px 12px #1f3d320f}.message-row.assistant .bubble{background:#fff;border:1px solid var(--line);border-bottom-left-radius:5px}.message-row.user .bubble{color:#fff;background:linear-gradient(145deg,var(--blue),#144e82);border-bottom-right-radius:5px;box-shadow:0 5px 15px #155fa02e}.meta{margin:4px 4px 0;color:#89958f;font-size:10px}.message-row.user .meta{text-align:right}
.sources{display:grid;gap:5px;margin-top:10px;padding-top:9px;border-top:1px solid #6981762e}.source{display:flex;align-items:center;gap:7px;color:inherit;font-size:11px;font-weight:650}.source svg{width:13px;height:13px;flex:none}.suggestions{display:flex;flex-wrap:wrap;gap:7px;margin:2px 0 18px 36px}.quick-reply{border:1px solid #cfe0d8;border-radius:999px;padding:8px 11px;color:var(--green-dark);background:#fff;cursor:pointer;font-size:11.5px;transition:.16s ease}.quick-reply:hover{border-color:var(--green);background:var(--green-soft);transform:translateY(-1px)}
.typing-row{display:flex;align-items:flex-end;gap:8px;margin-bottom:14px}.typing{display:flex;gap:4px;padding:13px 15px;border-radius:16px 16px 16px 5px;border:1px solid var(--line);background:#fff}.typing i{width:6px;height:6px;border-radius:50%;background:#829189;animation:bounce 1.1s infinite}.typing i:nth-child(2){animation-delay:.14s}.typing i:nth-child(3){animation-delay:.28s}.notice{margin:10px 12px 0;padding:10px 12px;border:1px solid #f0d27b;border-radius:12px;background:#fff8df;color:#684d00;font-size:12px}
.composer-wrap{padding:11px 12px 12px;background:#fff;border-top:1px solid var(--line)}.composer{display:flex;align-items:flex-end;gap:6px;padding:5px 5px 5px 8px;border:1px solid #d8e1dd;border-radius:18px;background:#fafcfb;transition:.16s}.composer:focus-within{border-color:#69a995;box-shadow:0 0 0 3px #006a4e17;background:#fff}.composer textarea{flex:1;resize:none;min-height:38px;max-height:110px;border:0;outline:0;padding:9px 5px;background:transparent;color:var(--ink);line-height:1.4}.composer textarea::placeholder{color:#8a9691}.tool,.send{flex:0 0 auto;width:38px;height:38px;border:0;border-radius:13px;cursor:pointer;display:grid;place-items:center}.tool{color:#65766e;background:transparent}.tool:hover,.tool.active{color:var(--green);background:var(--green-soft)}.send{color:#fff;background:linear-gradient(145deg,var(--green),var(--green-dark));box-shadow:0 5px 12px #004b3633}.send:disabled{opacity:.42;box-shadow:none;cursor:default}.tool svg,.send svg{width:18px;height:18px}.footer-note{text-align:center;margin-top:7px;color:#97a19c;font-size:9.5px}.bubble a{color:inherit;font-weight:700}
button:focus-visible,textarea:focus-visible{outline:3px solid #f4b41ab3;outline-offset:2px}@keyframes bounce{0%,60%,100%{transform:translateY(0);opacity:.55}30%{transform:translateY(-4px);opacity:1}}@keyframes appear{from{opacity:0;transform:translateY(12px) scale(.98)}}@media(prefers-reduced-motion:no-preference){.panel{animation:appear .2s ease-out}}@media(max-width:480px){:host{right:10px;bottom:10px}.panel{width:calc(100vw - 20px);height:calc(100dvh - 20px);border-radius:22px}.launcher{width:68px;height:68px;border-width:5px}}
`;
